---
title: "GLD Lightning data"
author: "Anna Talucci"
date: "2024-03-07"
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview

GLD Data 2016-2022

**What this script does**
This script 


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```

# Data

## vector of data files
original data in "../data/GoogleDriveCsvFolder/"
```{r}
f <- list.files(path = "../data/lightningData/GLD/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```

# View data frames

## 2016
```{r}
read.csv(f[1], header = TRUE) 
read.csv(f[2], header = TRUE) 
read.csv(f[3], header = TRUE) 
read.csv(f[4], header = TRUE) 
read.csv(f[5], header = TRUE) 
read.csv(f[6], header = TRUE) 
```

```{r}
read.csv(f[7], header = TRUE) 
read.csv(f[8], header = TRUE) 
read.csv(f[9], header = TRUE) 
read.csv(f[10], header = TRUE) 
read.csv(f[11], header = TRUE) 
read.csv(f[12], header = TRUE) 
```

## 2017

```{r}
read.csv(f[13], header = TRUE) 
read.csv(f[14], header = TRUE) 
read.csv(f[15], header = TRUE) 
read.csv(f[16], header = TRUE) 
read.csv(f[17], header = TRUE) 
read.csv(f[18], header = TRUE) 
```

```{r}
read.csv(f[19], header = TRUE) 
read.csv(f[20], header = TRUE) 
read.csv(f[21], header = TRUE) 
read.csv(f[22], header = TRUE) 
read.csv(f[23], header = TRUE) 
read.csv(f[24], header = TRUE) 
```

## 2018

```{r}
read.csv(f[25], header = TRUE) 
read.csv(f[26], header = TRUE) 
read.csv(f[27], header = TRUE) 
read.csv(f[28], header = TRUE) 
read.csv(f[29], header = TRUE) 
read.csv(f[30], header = TRUE) 
```

```{r}
read.csv(f[31], header = TRUE) 
read.csv(f[32], header = TRUE) 
read.csv(f[33], header = TRUE) 
read.csv(f[34], header = TRUE) 
read.csv(f[35], header = TRUE) 
read.csv(f[36], header = TRUE) 
```

## 2019

```{r}
read.csv(f[37], header = TRUE) 
read.csv(f[38], header = TRUE) # No data??
read.csv(f[39], header = TRUE) 
read.csv(f[40], header = TRUE) 
read.csv(f[41], header = TRUE) 
read.csv(f[42], header = TRUE) 
```

```{r}
read.csv(f[43], header = TRUE) 
read.csv(f[44], header = TRUE) 
read.csv(f[45], header = TRUE) 
read.csv(f[46], header = TRUE) 
read.csv(f[47], header = TRUE) 
read.csv(f[48], header = TRUE) 
```

## 2020

```{r}
read.csv(f[49], header = TRUE) 
read.csv(f[50], header = TRUE) 
read.csv(f[51], header = TRUE) # march 2 data points
read.csv(f[52], header = TRUE) # april no data?
read.csv(f[53], header = TRUE) 
read.csv(f[54], header = TRUE) 
```

```{r}
read.csv(f[55], header = TRUE) 
read.csv(f[56], header = TRUE) 
read.csv(f[57], header = TRUE) 
read.csv(f[58], header = TRUE) 
read.csv(f[59], header = TRUE) 
read.csv(f[60], header = TRUE) 
```

## 2021

```{r}
read.csv(f[61], header = TRUE) 
read.csv(f[62], header = TRUE) 
read.csv(f[63], header = TRUE) 
read.csv(f[64], header = TRUE) 
read.csv(f[65], header = TRUE) 
read.csv(f[66], header = TRUE) 
```

```{r}
read.csv(f[67], header = TRUE) 
read.csv(f[68], header = TRUE) 
read.csv(f[69], header = TRUE) 
read.csv(f[70], header = TRUE) 
read.csv(f[71], header = TRUE) 
read.csv(f[72], header = TRUE) 
```

## 2022

```{r}
read.csv(f[73], header = TRUE) 
read.csv(f[74], header = TRUE) 
read.csv(f[75], header = TRUE) 
read.csv(f[76], header = TRUE) 
read.csv(f[77], header = TRUE) 
read.csv(f[78], header = TRUE) 
```

```{r}
read.csv(f[79], header = TRUE) 
read.csv(f[80], header = TRUE) 
read.csv(f[81], header = TRUE) 
read.csv(f[82], header = TRUE) 
read.csv(f[83], header = TRUE) 
read.csv(f[84], header = TRUE) 
```